### ISSUE TITLE
Add an AUTHORS file.

### ISSUE THREAD

**Issue by hodgestar** [CTPUG/pygame_cffi#11]
A bunch of different people have now contributed to pygame_cffi. We should give them credit.

**Comment by GertBurger** [comment]
# git log --format='%aN <%aE>'|sort -f|uniq
Armin Rigo <arigo@tunes.org>                                                           
Gert Burger <gertburger@gmail.com>
Jeremy Thurgood <firxen@gmail.com>
John Cupitt <jcupitt@gmail.com>
Maciej Fijalkowski <fijall@gmail.com>
Neil Muller <drnlmuller+github@gmail.com>
Neil <neil@dip.sun.ac.za>
Piet Delport <pjdelport@gmail.com>
Rizmari Versfeld <rizmari@praekelt.com>
Rizmari Versfeld <rizmari@praekeltconsulting.com>
Rizmari Versfeld <rizziepit@gmail.com>
Simon Cross <hodgestar@gmail.com>

**Comment by drnlm** [comment]
closed by #30
