### ISSUE TITLE
Please add pygame.mask

### ISSUE THREAD

**Issue by somvisai** [CTPUG/pygame_cffi#15]
I'm using pygame.mask to detect object in TMX please update it

**Comment by arigo** [comment]
This looks like a medium-big module.  See its source at https://bitbucket.org/pygame/pygame/src/default/src/mask.c .  At this point it's unlikely someone will make the work just for fun, but contributions from you would be very welcome.

**Comment by hodgestar** [comment]
What we've done in the past for these kinds of modules is to copy across
parts of the underlying C code from pygame. The same approach might work
for us here.

**Comment by hodgestar** [comment]
@somvisai Are there specific mask functions that are more important to you than others? Or do you need all of them for mask to be useful to you?

**Comment by drnlm** [comment]
#25 has been merged, so pygame.mask is now available.
