### ISSUE TITLE
ImportError: No module named pygame._sdl_c

### ISSUE THREAD

**Issue by Baekalfen** [CTPUG/pygame_cffi#16]
I seem to have a problem with this module on Mac OS X 10.11 Golden Master.

Running "import pygame" causes the following error:
```
Python 2.7.10 (f3ad1e1e1d6215e20d34bb65ab85ff9188c9f559, Sep 21 2015, 15:59:29)
[PyPy 2.6.1 with GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import pygame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/pypy/2.6.1/libexec/site-packages/pygame_cffi-0.0.1-py2.7-macosx-10.11-x86_64.egg/pygame/__init__.py", line 3, in <module>
    from pygame.color import Color
  File "/usr/local/Cellar/pypy/2.6.1/libexec/site-packages/pygame_cffi-0.0.1-py2.7-macosx-10.11-x86_64.egg/pygame/color.py", line 3, in <module>
    from pygame._sdl import ffi, sdl
  File "/usr/local/Cellar/pypy/2.6.1/libexec/site-packages/pygame_cffi-0.0.1-py2.7-macosx-10.11-x86_64.egg/pygame/_sdl.py", line 1, in <module>
    from pygame._sdl_c import ffi
ImportError: No module named pygame._sdl_c
>>>>
```

To install it, I ran:
```
brew install pypy cairo jpeg
git clone https://github.com/CTPUG/pygame_cffi.git
cd pygame_cffi
pypy setup.py build build_ext -n -I/usr/local/include
sudo pypy setup.py install build_ext -n -I/usr/local/include
```

I included "/usr/local/include" because it couldn't find "jpeglib.h"

**Comment by hodgestar** [comment]
It looks like you're trying to set up a development install of pygame_cffi. If that is you're intention, we recently documented how to do that -- https://github.com/CTPUG/pygame_cffi/blob/master/README.md#local-development.

If you just want to install pygame_cffi from PyPI, `pip install pygame_cffi` should now work (once you have the various C library dependencies installed -- see https://github.com/CTPUG/pygame_cffi/blob/master/README.md#requirements for the list).

Let us know if this helps.

**Comment by talljosh** [comment]
I'm seeing the same traceback on Ubuntu. To install, I ran:

```
pypy -m pip install --user pygame_cffi
```

My traceback looks like this:
```
Python 2.7.8 (2.5.0+dfsg-2, Feb 12 2015, 05:23:41)
[PyPy 2.5.0 with GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import pygame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/josh/.local/lib/pypy2.7/site-packages/pygame/__init__.py", line 3, in <module>
    from pygame.color import Color
  File "/home/josh/.local/lib/pypy2.7/site-packages/pygame/color.py", line 3, in <module>
    from pygame._sdl import ffi, sdl
  File "/home/josh/.local/lib/pypy2.7/site-packages/pygame/_sdl.py", line 1, in <module>
    from pygame._sdl_c import ffi
ImportError: No module named pygame._sdl_c
``

**Comment by talljosh** [comment]
I fixed this by updating to latest stable PyPy (and corresponding version of cffi). I had been using the version of PyPy in the Ubuntu package repositories, which was woefully out of date.

After upgrading PyPy using the PPA [here](https://launchpad.net/~pypy/+archive/ubuntu/ppa), I had to purge `pip`'s cache directory to get it to install `python-cffi` correctly. After that everything worked fine.

**Comment by hodgestar** [comment]
@talljosh Thanks for reporting how you sorted things out! I'm closing this for now since it seems unrelated to pygame-cffi itself.
