### ISSUE TITLE
Add support for pygame.math.

### ISSUE THREAD

**Issue by hodgestar** [CTPUG/pygame_cffi#53]
Currently we don't have this module.

**Comment by ajoubertza** [comment]
Started work on this in forked repo: https://github.com/ajoubertza/pygame_cffi/tree/issue-53-add-pygame-math.  Some implementation of Vector2, none for Vector3 yet.  Pulled in tests from pygame - most are still failing at this stage.

**Comment by drnlm** [comment]
Added by #74
