### ISSUE TITLE
pygame_cff unpack_rect is too restrictive

### ISSUE THREAD

**Issue by drnlm** [CTPUG/pygame_cffi#60]
with stock pygame:

```>> pygame.surface.Surface((120.0, 122.8))
<Surface(120x122x32 SW)>```

With pygame_cffi

````>> pygame.surface.Surface((122.0, 122.8))
....
TypeError: expected tuple of two integers but got <type 'tuple'>```

This causes problems with programs that pass floats (usually created by some mathematical operation) when creating surfaces

**Comment by drnlm** [comment]
unpack_rect is also used in display.py, where pygame also doesn't allow floats.

stock.pygame
```>> pygame.display.set_mode((300.3, 300.3))
....
TypeError: integer argument expected, got float```

Whether this inconsistency in the pygame API is something we need to match  is a debatable point.

**Comment by TiberiumPY** [comment]
@drnlm This is used in a lot of games (I explored pygame.org website for hours)

**Comment by drnlm** [comment]
We should  accept floats in pygame.surface.Surface - being more restrictive than pygame there isn't useful.

If you're referring to my "inconsistency" comment, that's about whether preventing floats in pygame.display.set_mode is something we need to match. Nothing should break if we're more permissive than pygame in places.

**Comment by TiberiumPY** [comment]
@drnlm I agree with your improvements, check out my fork of pygame_cffi (this places there I fixed it - there some games could supply floats)

**Comment by hodgestar** [comment]
@TiberiumPY If you have fixed things in a fork, could you create pull requests will your fixes so we can merge them in?

**Comment by TiberiumPY** [comment]
@hodgestar they're ugly (I just use list comprehension to convert floats to int, but I can't edit C code, because I'm not familiar with it)
