### ISSUE TITLE
pygame.transform.smoothscale not implemented

### ISSUE THREAD

**Issue by randm-prgrmr** [CTPUG/pygame_cffi#7]
Anyone have any plans to implement?

**Comment by hodgestar** [comment]
Not that I know of. Want to give implementing it a try?

**Comment by randm-prgrmr** [comment]
Yes I plan to give it a shot, I had a cursory look at the scale function that is already implemented but its hardly relevant to the smoothscale function -- pygame's one has inline asm and stuff, I made an issue hoping someone with more c/asm experience would try it in case I'm not able to pull it off :)

**Comment by hodgestar** [comment]
Make a PR with what you have and shout if you run into trouble and I'll try
take a look. I'm not a C/ASM expert either but hopefully we can rope in
some gurus if needed. :)

**Comment by drnlm** [comment]
The optimised MMX and SSe versions aren't implemented, but the generic C implementation has been added in #14
