### ISSUE TITLE
pygame.joystick

### ISSUE THREAD

**Issue by RyanHope** [CTPUG/pygame_cffi#8]
Clearly this is not implemented yet. Is there an eta on this?

**Comment by hodgestar** [comment]
I don't know of anyone whose contributed so far who has a joystick to test with. Are you up for helping test a pull-request if someone works on it? The module doesn't look too big.

**Comment by RyanHope** [comment]
Yes I can test what ever you push.

**Comment by hodgestar** [comment]
@RyanHope (or anyone else with a joystick): Want to give #13 a try? I wrote the code without a joystick (so pretty blind). Feel free to post bugs, complaints or patches here and I'll try sort them out.

**Comment by RyanHope** [comment]
yeah I will get to this this week i think

On Sun, May 31, 2015 at 3:22 PM, Simon Cross <notifications@github.com>
wrote:

> @RyanHope <https://github.com/RyanHope> (or anyone else with a joystick):
> Want to give #13 <https://github.com/CTPUG/pygame_cffi/pull/13> a try? I
> wrote the code without a joystick (so pretty blind). Feel free to post
> bugs, complaints or patches here and I'll try sort them out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CTPUG/pygame_cffi/issues/8#issuecomment-107238335>.
>



-- 
Ryan Hope, M.S.
CogWorks Lab
Cognitive Science Department
Rensselaer Polytechnic Institute

**Comment by hodgestar** [comment]
Tx!

**Comment by hodgestar** [comment]
PR #13 has landed.
